[project]
name = "tasks"
version = "0.1.0"
description = "Minimal Flask Task Board (SQLite) with dependencies and timeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
]

[tool.uv]
